# Note:  This is an example config, see habitat_baselines/config/pointnav/ppo_pointnav.yaml
# for better hyperparameters for actual training

DATA_PATH_SET: "/home/userone/workspace/bed1/ppo_custom/data/datasets/pointnav/habitat-test-scenes/v1/{split}/{split}.json.gz"
SCENE_DIR_SET: "/home/userone/workspace/bed1/ppo_custom/data/scene_datasets"
BASE_TASK_CONFIG_PATH: "/home/userone/workspace/bed1/habitat-api/configs/tasks/pointnav.yaml"
EVAL_CKPT_PATH_DIR: "/home/userone/workspace/bed1/ppo_custom/tmp/new_checkpoints"
CHECKPOINT_FOLDER: "/home/userone/workspace/bed1/ppo_custom/tmp/new_checkpoints"
VIDEO_DIR: "/home/userone/workspace/bed1/ppo_custom/tmp/video_dir"
TRAINER_NAME: "ppo"
ENV_NAME: "NavRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
# VIDEO_OPTION: ["disk", "tensorboard"]
VIDEO_OPTION: ["disk"]
# To evaluate on all episodes, set this to -1
TEST_EPISODE_COUNT: 10
NUM_PROCESSES: 1
#SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
SENSORS: ["RGB_SENSOR"]
NUM_UPDATES: 1000
LOG_INTERVAL: 10
CHECKPOINT_INTERVAL: 50

RL:
  PPO:
    # ppo params
    clip_param: 0.1
    ppo_epoch: 4
    num_mini_batch: 1
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.5
    num_steps: 128
    hidden_size: 512
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: True
    use_linear_lr_decay: True
    reward_window_size: 50
